using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MasterMindCompetition.Logic { //this namespace handles the shared logic of all sub-games
    enum Colour { Red, Green, Blue, Yellow, Orange}

    abstract class MastermindGame { //abstract as a game must be of a certain type (ie auto-codemaker)
        protected Code target; //the code generated by the codemaker
        protected List<Code> guessCodes; //holds the codebreaker's guesses
        protected ICodemakerHostForm hostForm; //reference back to GUI
        protected int codeLength;
        public int maxGuesses { get; set; } //the max number of guesses that may be made
        

        protected MastermindGame(ICodemakerHostForm _form) { //initialise the game
            hostForm = _form; //update the host form
        }

        public virtual void newGame(int _maxGuesses, int _codeLength) {

            //initialise some vars
            maxGuesses = _maxGuesses;
            codeLength = _codeLength;

            initialiseGame();//run first stages of game (generating target code, etc)
        } //create a new game


        protected abstract void initialiseGame(); //run first stages of game (generating target code, etc)

        //properties to allow limited access to some private members from public scope
        public List<Code> GuessCodes { get { return guessCodes; } } //allow readonly access to the guessed codes
    }
}
